apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-debug"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: "{{image}}"
  replicas:
    min: 1
    max: 1
  ttl: "{{ttl}}"
  prometheus:
    enabled: false
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  accessPolicy:
    outbound:
      external:
        - host: www.vg.no
      rules:
        - application: dp-debug
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
