name: Build and push

on:
  workflow_dispatch:
    environment:
      description: Environment to deploy
      required: true
      default: dev-gcp
      type: choice
      options:
        - dev-gcp
        - dev-fss
        - prod-gcp
        - prod-fss

    ttl:
      description: TTL for app (f.ex. 1h, 1d, 1w, 1m)
      required: true
      default: 1h

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          salsa: true
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy to ${{ inputs.environment }}
        env:
          CLUSTER: ${{ inputs.environment }}
          RESOURCE: .nais/nais.yaml
          PRINT_PAYLOAD: true
          VAR: image=${{ needs.build.outputs.image }}, ttl=${{ inputs.ttl }}
